# =======================
# Configuration générale
# =======================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assistant_medecin_db?useSSL=false&serverTimezone=UTC
    username: root
    password: marya123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Désactiver H2 Console
spring:
  h2:
    console:
      enabled: false

# =======================
# CORS pour Angular
# =======================
spring:
  web:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# =======================
# Eureka Client
# =======================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# =======================
# Logging
# =======================
logging:
  level:
    org.springframework.web: INFO
    com.example.assistantmedecinservicebackend: DEBUG
